# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0003_alter_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('default.association',),
        ),
        migrations.CreateModel(
            name='Nonce',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('default.nonce',),
        ),
        migrations.CreateModel(
            name='UserSocialAuth',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('default.usersocialauth',),
        ),
    ]
