# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_alter_email_max_length'),
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('default.code',),
        ),
    ]
